# Nacos 配置（容器间访问）
# 使用 Docker 网络中的服务名或宿主机特殊地址
node.id=node1
server.port=8080
spring.application.name=nacos-demo-service
spring.cloud.nacos.config.server-addr=host.docker.internal:8848
spring.cloud.nacos.config.namespace=public
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos

spring.cloud.nacos.discovery.server-addr=host.docker.internal:8848
spring.cloud.nacos.discovery.namespace=public
spring.cloud.nacos.discovery.group=DEFAULT_GROUP
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos

spring.config.import=optional:nacos:nacos-demo-service-docker.properties
# Kafka 配置


# 其他配置保持不变...
feign.sentinel.enabled=true
logging.config=classpath:logback-spring.xml
logging.file.name=logs/nacos-demo-service.log


# Kafka 基础配置
spring.kafka.bootstrap-servers=host.docker.internal:9093
# 生产者配置
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
#spring.kafka.consumer.group-id=order-events-consumer-${server.port}
#spring.kafka.consumer.client-id=consumer-order-events-${server.port}
## 消费者配置
spring.kafka.consumer.group-id=my-consumer-group-${server.port}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
logging.level.org.apache.kafka.clients=ERROR
# 主题配置
app.kafka.topics.user-events=user-events-topic
app.kafka.topics.order-events=order-events-topic
app.kafka.topics.notification=notification-topic


# 启用多部分文件上传
spring.servlet.multipart.enabled=true
# 单个文件最大大小 (例如 2MB)
spring.servlet.multipart.max-file-size=2MB
# 整个请求最大大小 (例如 10MB)
spring.servlet.multipart.max-request-size=10MB
# 自定义上传目录（可选）
file.upload-dir=./uploads

# JWT 配置
jwt.secret-key.access=your-super-secure-256-bit-secret-for-access-token-here
jwt.secret-key.refresh=a-different-super-secure-secret-for-refresh-token-here
jwt.expiration.access=5000
jwt.expiration.refresh=1209600000

# 服务器配置
server.address=0.0.0.0

